[package]
name = "crabtype"
version = "1.0.0"
authors = ["einsJannis"]
readme = "README.md"
license-file = "LICENSE"
description = "A TUI based alternative to MonkeyType"

[dependencies]
ratatui="*"
crossterm="*"
rand="*"
serde = { version = "*", features = ["derive"] }
toml="*"
