[package]
name = "typing-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui="*"
crossterm="*"
rand="*"
serde = { version = "*", features = ["derive"] }
toml="*"
